import pandas as pd
import google.generativeai as genai
from API_keys import key_gemini
from PIL import Image
from Gemini_agents import process_user_input
from local import get_similar_memes
from recommendation_filepaths import main
import os

# Meme Retrieval Mode: user wants to find memes that match the query sentiment/topic
meme_queries = [
    "student life memes",
    "final exam memes",
    "data science memes",
    "machine learning memes",
    "math major memes",
    "philosophy class memes",
    "dorm room cooking memes",
    "lecture hall memes",
    "internship search memes",
    "job application memes",
    "remote work memes",
    "AI revolution memes",
    "coding bug memes",
    "stack overflow memes",
    "coffee vs tea memes",
    "group project memes",
    "procrastination with YouTube memes",
    "college tuition memes",
    "flatmate cleaning schedule memes",
    "Linux vs Windows memes",
    "Git commit struggles memes",
    "Zoom call fails memes",
    "freshman orientation memes",
    "exam cramming memes",
    "public speaking anxiety memes",
    "PowerPoint presentation memes",
    "printer jam memes",
    "student loan memes",
    "deadline panic memes",
    "brainstorming session memes",
    "Google Docs chaos memes",
    "thesis writing memes",
    "scheduling conflict memes",
    "academic advisor memes",
    "unread emails memes",
    "conference call memes",
    "tech support frustration memes",
    "computer lab late night memes",
    "whiteboard brainstorming memes",
    "data visualization memes",
    "excel spreadsheet chaos memes",
    "capstone project memes",
    "overfitting model memes",
    "deep learning black box memes",
    "train-validation split memes",
    "data preprocessing memes",
    "natural language processing memes",
    "presentation day memes",
    "lab partner memes",
    "internship onboarding memes",
    "meeting that could be email memes",
    "waiting for render memes",
    "debugging all night memes",
    "exam curve memes",
    "grad school application memes",
    "research paper citation memes",
    "impromptu quiz memes",
    "impulse online shopping memes",
    "burnt toast in dorm memes",
    "college roommate memes",
    "oversleeping memes",
    "alarm clock betrayal memes",
    "meme about sleep schedule",
    "new semester resolution memes",
    "calendar sync issues memes",
    "laptop overheating memes",
    "computer science dropout memes",
    "Python indentation error memes",
    "JavaScript bug memes",
    "SQL query fail memes",
    "computer crash before deadline memes",
    "hunger during lecture memes",
    "cafeteria food review memes",
    "campus Wi-Fi memes",
    "parking ticket on campus memes",
    "professor doesnt post slides memes",
    "group chat silence memes",
    "printer out of ink memes",
    "late library return memes",
    "coding bootcamp memes",
    "online class distraction memes",
    "webcam off during zoom memes",
    "LinkedIn profile update memes",
    "job rejection memes",
    "AI writing essay memes",
    "chegg vs studying memes",
    "blue screen of death memes",
    "wireless mouse battery dead memes",
    "overbooked exam center memes",
    "exam center wifi down memes",
    "too many tabs open memes",
    "Github merge conflict memes",
    "error 404 life not found memes",
    "final grade surprise memes",
    "screenshotting Zoom memes",
    "silent lecture memes",
    "bad group leader memes",
    "campus squirrel memes",
    "first snow memes",
    "weekend lab session memes",
    "graduate defense memes",
    "confusing syllabus memes",
    "email signature memes",
    "academic conference memes",
    "memes about the pain of debugging a project minutes before the deadline",
    "memes capturing the awkward silence during a Zoom breakout room",
    "relatable memes about struggling to stay awake in 8am lectures",
    "memes illustrating the chaos of group projects when no one replies",
    "memes that compare real-world job hunting to academic achievements",
    "memes highlighting the disconnect between CS theory and real coding",
    "memes about the anxiety of accidentally clicking reply all on an email",
    "memes expressing frustration over poorly explained assignment prompts",
    "memes that joke about students living off instant noodles during finals",
    "memes showing the desperation of submitting to Turnitin at 11:59 PM",
    "memes that portray the emotional rollercoaster of reading teacher feedback",
    "memes on the paradox of needing experience to get experience in tech jobs",
    "memes that capture the existential dread of graduating with student debt",
    "memes joking about how caffeine replaces water during finals week",
    "memes about the confusion of opening a class discussion post thread",
    "memes showing the pain of finding a bug and fixing it for 6 hours",
    "memes that mock the overuse of the phrase we value your feedback",
    "memes about overpreparing for a midterm only to realize its open-book",
    "memes that exaggerate the difference between syllabus promises and reality",
    "memes expressing the confusion around version control errors in Git",
    "memes about the student who always submits 5 seconds before the deadline",
    "memes about surviving off leftover pizza and bad coffee during finals",
    "memes about professors assigning 3 essays due on the same day",
    "memes exaggerating the emotional support students get from their pets",
    "memes about being ghosted by your group project teammates",
    "memes about the anxiety of seeing a blank Google Doc the night before",
    "memes that joke about attending office hours as a form of therapy",
    "memes about students coping with 8 tabs of Stack Overflow open",
    "memes about pretending to understand a lecture for participation points",
    "memes about professors asking you to turn on your camera at 8 AM",
    "memes about someone fixing the code by adding random print statements",
    "memes about missing the assignment link hidden in the syllabus",
    "memes showing students using AI to do their homework last minute",
    "memes about struggling to find motivation after mid-semester break",
    "memes making fun of overly complex academic jargon in research papers",
    "memes about debugging only to realize you forgot a semicolon",
    "memes portraying the panic of a corrupted hard drive before submission",
    "memes mocking people who say college is the best time of your life",
    "memes exaggerating how group projects are survival of the fittest",
    "memes showing the hierarchy of dorm room microwave ownership",
    "memes about professors saying this wont be on the test (it is)",
    "memes that mock students who flex coding on LinkedIn but cant debug",
    "memes about fighting for outlets in crowded study lounges",
    "memes about using ChatGPT to understand what GPT even means",
    "memes on reusing last semesters assignment and praying no one notices",
    "memes about student burnout disguised as dark humor",
    "memes about lab reports turning into creative writing exercises",
    "memes on scheduling meetings that never happen due to conflicts",
    "memes on getting ghosted by internship applications",
    "memes mocking the debate between light mode vs dark mode",
    "memes showing students calculating GPA like doing rocket science",
    "memes showing the irony of attending a time management workshop late",
    "memes about attending a class just for the attendance points",
    "memes about online classes where no one turns on their mic or camera",
    "memes about crashing Excel by importing too much data",
    "memes mocking the idea of networking on LinkedIn with strangers",
    "memes comparing pre-semester optimism to finals week despair",
    "memes showing students who treat syllabus week like vacation",
    "memes about losing all tabs after a Chrome crash during research",
    "memes about professors who take attendance after class ends",
    "memes showing students paying rent to live in the library",
    "memes comparing summer classes to academic bootcamps",
    "memes joking about coffee becoming a personality trait",
    "memes about accidentally submitting the wrong PDF",
    "memes about someone using Comic Sans in a group presentation",
    "memes about waiting for grades like waiting for election results",
    "memes comparing college group chats to cursed meme dumps",
    "memes about professors who mute all fun during presentations",
    "memes making fun of syllabus voice vs final exam voice",
    "memes about mispronouncing technical words in class discussions",
    "memes mocking inspirational quotes that dont help during finals",
    "memes about treating lab safety rules like guidelines",
    "memes about using memes as legitimate study material",
    "memes about class participation being a form of social anxiety exposure",
    "memes that portray LinkedIn as Facebook for career overachievers",
    "memes that show how job interviews feel like boss fights",
    "memes about treating thesis defense like courtroom drama",
    "memes about essay feedback that says good job and then gives a C",
    "memes on hiding your burnout under a smile in Zoom class",
    "memes that describe submitting code that only works once",
    "memes about students going from I got this to crying in one week",
    "memes on coding late at night and hearing imaginary compiler voices",
    "memes about students negotiating extensions like hostage deals",
    "memes showing the irony of procrastination workshops being ignored",
    "memes about starting an assignment that was due yesterday",
    "memes mocking motivational posters in depressing lecture halls",
    "memes showing students dressed for Zoom from the waist up",
    "memes about losing your work because you didnt save before crash",
    "memes about college diets being energy drinks and frozen burritos",
    "memes about students sacrificing their sleep to meet deadlines",
    "memes about last-minute presentation slides being memes themselves",
    "memes about students calculating if 60% is enough to pass",
    "memes about realizing the rubric never matched the actual grading",
    "memes showing the moment when someone deletes the shared file",
    "memes about recording lectures but never watching them",
    "memes that compare syllabus week promises to actual midterms",
    "memes about students identifying emotionally with their error logs",
    "memes showing the disconnect between class lectures and exams",
    "memes about professors asking for short answers in 1000 words",
    "memes on writing citations like casting spells"
]

# Template Retrieval Mode: user is looking for a specific meme format/template
template_queries = [
    "distracted boyfriend meme template",
    "Drake yes/no meme template",
    "two-button choice meme template",
    "change-my-mind meme template",
    "Is this a pigeon? meme template",
    "expanding brain meme template",
    "gru plan meme template",
    "spongebob mocking meme template",
    "surprised pikachu meme template",
    "opinion hot take button meme template",
    "galaxy brain meme template",
    "they had us in the first half meme template",
    "left exit 12 off-ramp meme template",
    "american chopper argument meme template",
    "mocking SpongeBob meme template",
    "unsettled Tom meme template",
    "monkey puppet meme template",
    "spongebob iight imma head out meme template",
    "dude with sign meme template",
    "who killed Hannibal meme template",
    "grasping butterfly meme template",
    "I fear no man but that thing meme template",
    "scroll of truth meme template",
    "how tough are you meme template",
    "hard to swallow pills meme template",
    "aight imma head out meme template",
    "boardroom suggestion meme template",
    "always has been meme template",
    "me explaining meme template",
    "pikachu face meme template",
    "bus stop wait meme template",
    "first day vs last day meme template",
    "friends laughing at you meme template",
    "sign guy meme template",
    "tony stark eye roll meme template",
    "wojak pointing meme template",
    "chad vs virgin meme template",
    "cheating boyfriend caught meme template",
    "unhelpful high school teacher meme template",
    "thats none of my business meme template",
    "my plans vs 2020 meme template",
    "pointing Spider-Man meme template",
    "billionaire starter pack meme template",
    "grumpy cat meme template",
    "blank starter pack meme template",
    "evil Kermit meme template",
    "lego yoda wisdom meme template",
    "dark Kermit meme template",
    "Spiderman mask off meme template",
    "LeBron decision meme template",
    "woman yelling at cat meme template",
    "this is fine meme template",
    "philosoraptor meme template",
    "distracted astronaut meme template",
    "the floor is lava meme template",
    "wrong answers only meme template",
    "wait its all meme template",
    "nobody meme template",
    "Netflix adaptation meme template",
    "guess Ill die meme template",
    "man looking out window meme template",
    "deep fried meme template",
    "stock photo guy meme template",
    "long neck guy meme template",
    "confused math lady meme template",
    "lego walk meme template",
    "success kid meme template",
    "ancient aliens guy meme template",
    "inhaling seagull meme template",
    "dramatic chipmunk meme template",
    "zoom in enhance meme template",
    "deal with it sunglasses meme template",
    "rickroll meme template",
    "I am once again asking meme template",
    "no one literally no one meme template",
    "when the impostor is sus meme template",
    "futurama shut up and take my money meme template",
    "arthur fist meme template",
    "dumb ways to die meme template",
    "teletubbies scary edit meme template",
    "Buzz Lightyear everywhere meme template",
    "infinity war what did it cost meme template",
    "batman slapping robin meme template",
    "press F to pay respects meme template",
    "facebook arguments meme template",
    "crying jordan meme template",
    "math teacher vs real life meme template",
    "your brain on meme template",
    "school expectations vs reality meme template",
    "karen haircut meme template",
    "middle child meme template",
    "dad joke meme template",
    "IT support meme template",
    "404 error meme template",
    "keyboard warrior meme template",
    "lagging Zoom meme template",
    "pirate software meme template",
    "dont talk to me or my son meme template",
    "scream cat meme template",
    "we were on a break meme template",
    "water bottle flip meme template",
    "meme inception template",
    "find the distracted boyfriend meme template where the boyfriend represents procrastination and the girlfriend is time management",
    "search for the Drake no-yes meme template often used to contrast bad vs good study habits",
    "get the galaxy brain meme template typically used to represent increasingly absurd logic",
    "retrieve the two-button decision meme template used to portray conflicting priorities in college life",
    "show the change-my-mind meme template frequently used to express controversial academic opinions",
    "identify the Is this a pigeon? meme template for memes about mislabeling complex concepts",
    "find the gru plan meme template often used to show plans backfiring on yourself",
    "locate the they had us in the first half meme template used for unexpected plot twists",
    "retrieve the woman yelling at cat meme template used to contrast irrational anger and indifference",
    "get the expanding brain meme template used for mocking superficial to absurdly deep ideas",
    "use the press F to pay respects meme template often used for dramatic failures",
    "get the this is fine meme template for situations where chaos is ignored",
    "search for the boardroom suggestion meme template showing rejected reasonable ideas",
    "locate the always has been astronaut meme template for sudden realizations or denial",
    "identify the two Spidermen pointing at each other template used to illustrate identity confusion",
    "retrieve the hard to swallow pills meme template used for harsh truths",
    "get the mocking SpongeBob meme template for sarcastic or exaggerated mimicry",
    "fetch the unhelpful high school teacher meme template for poor guidance satire",
    "show the monkey puppet looking away meme template used to portray awkward avoidance",
    "search for the I am once again asking meme template to represent repetitive requests",
    "get the distracted astronaut meme template for memes with unexpected truths",
    "find the left exit ramp meme template representing impulsive decisions",
    "show the pikachu surprised face meme template used for fake surprise reactions",
    "retrieve the me explaining vs friend not listening meme template for one-sided convos",
    "get the gru pointing to plan that backfires meme used to show unintended outcomes",
    "find the success kid meme template commonly used to depict small victories",
    "fetch the Philosoraptor meme template used for overthinking mundane topics",
    "locate the Tony Stark eye roll meme template often used for sarcastic disapproval",
    "get the starter pack meme template for stereotype collections",
    "search for the woman yelling at man meme template used to show blame or overreaction",
    "retrieve the lego yoda wisdom meme template used for ironic ancient advice",
    "fetch the chad vs virgin meme template used to compare confidence vs insecurity",
    "locate the crying Jordan face meme template often edited into failure scenarios",
    "get the Buzz Lightyear everywhere template showing widespread problems",
    "find the Netflix adaptation meme template comparing expectations to reality",
    "identify the deep fried distorted meme template used for exaggerated chaos",
    "retrieve the Ight imma head out meme template to indicate quitting",
    "get the waiting skeleton at computer template for long loading or delays",
    "show the scroll of truth meme template where reality is ignored or rejected",
    "get the Batman slaps Robin meme template used for contradiction or correction",
    "search for hot take red button meme template to show polarizing choices",
    "locate the bad idea vs good idea template often used in tech/startup humor",
    "find the sponge bob fire room meme template to show chaotic acceptance",
    "get the inhaling seagull meme template used for loud proclamations",
    "identify the Doom Guy hugs Daisy meme template used for unexpectedly wholesome moments",
    "fetch the Arthur fist meme template for quiet anger",
    "show the boomer comic style meme template with intentionally outdated views",
    "search for the no one: literally no one: meme template for unsolicited actions",
    "get the LeBron decision press conference template used for exaggerated announcements",
    "locate the keyboard warrior meme template for online arguments",
    "retrieve the first day vs last day meme template showing dramatic changes",
    "show the me vs also me meme template for internal contradictions",
    "get the my plans vs 2020 template used for ironic disruption",
    "get the confused math lady meme template used to show mental overload",
    "fetch the evil Kermit vs good Kermit meme template representing internal conflict",
    "locate the is that a threat? meme template used for veiled warnings",
    "search for the wait its all meme template depicting hidden truths",
    "retrieve the zoom in enhance meme template for impossible expectations in tech",
    "get the Facebook arguments in comments template for online debates",
    "identify the middle child starter pack template to show overlooked stereotypes",
    "locate the meme inception template showing a meme inside a meme",
    "fetch the nervous sweating guy meme template used for panic or indecision",
    "get the guy blinking in disbelief meme template for sarcastic surprise",
    "retrieve the one does not simply walk into meme template for challenging tasks",
    "find the Futurama Fry - not sure if meme template for uncertain thoughts",
    "search for the tuxedo Winnie the Pooh meme template to show formal versions of ideas",
    "locate the if you could stop thatd be great meme template for passive-aggressive feedback",
    "identify the I fear no man but that thing meme template to show exaggerated fears",
    "get the screaming cat at dinner table meme template for irrational arguments",
    "find the I dont even know who you are meme template to show irrelevance",
    "fetch the hes speaking the language of the gods meme template for perfect solutions",
    "locate the you had one job meme template used for single-point failure humor",
    "retrieve the Zuckerberg at Congress template used for awkward or robotic responses",
    "get the Ive seen enough, Im satisfied meme template to represent quick judgment",
    "identify the how do you do, fellow kids? template for being out of touch",
    "search for the fastest things alive meme template to show speed comparisons",
    "find the thats bait meme template for manipulative clickbait or arguments",
    "locate the this ones for you meme template often used to attribute actions",
    "fetch the are ya winning, son? meme template for generational disconnect",
    "retrieve the doge vs cheems meme template used for old vs new comparisons",
    "get the its free real estate meme template for tempting but shady offers",
    "identify the American Chopper argument template for escalating debates",
    "search for the unexpected wholesome moment meme template used for emotional shifts",
    "locate the dont talk to me or my son ever again meme template for exaggerated disapproval",
    "get the John Cena you cant see me template for invisibility or absence metaphors",
    "fetch the Minecraft Youtuber intro parody template for exaggerated YouTube behavior",
    "retrieve the oh no! anyway meme template used to dismiss dramatic news",
    "locate the Wojak comic with brain sizes template showing evolution of thoughts",
    "identify the angry guy pointing at chart meme template for forced logic",
    "get the nuclear explosion behind calm person meme template for ignoring disaster",
    "fetch the person stuck in loop of time template for repetitive failures",
    "locate the the floor is lava meme template for avoidance behavior",
    "search for the invisible car driving through sign meme template for ignoring limits",
    "get the progress bar stuck at 99% meme template for nearly done tasks that never finish",
    "identify the strong doge vs weak doge meme template for skill comparisons",
    "fetch the anti-joke chicken meme template for subverting punchlines",
    "retrieve the IT crowd fire in office meme template for chaotic tech issues",
    "get the crash zoom on face meme template for dramatic realizations",
    "locate the cat vibing with headphones meme template for being in the zone",
    "find the overly attached girlfriend meme template for clingy or intense behavior",
    "identify the Shrek surprise face meme template for unexpected intrusions",
    "fetch the minion quotes with poor grammar template used for satire",
    "search for the no u reverse card meme template for playful comeback"
]

genai.configure(api_key=key_gemini) 

model_1 = genai.GenerativeModel("gemini-2.5-flash-preview-04-17", system_instruction= "You must always follow the rules.")

def gemini_evaluate_relevance(query, image_path):
    img = Image.open(image_path)
    prompt = f"""
You will be shown a query and a meme image. Evaluate how relevant the image is to the query on a 3-point scale:

2 = highly relevant 
1 = relevant
0 = not relevant

Relevance can be based on either **local context** or **global context**—use the higher of the two.

- **Local context** refers to user-generated elements such as the overlaid text on the meme, which may directly relate to the query topic.
- **Global context** refers to the underlying meme template or visual format, which may carry cultural, symbolic, or thematic relevance to the query, even without text.

Respond with only a single number: 2, 1, or 0.

Query: {query}
"""
    response = model_1.generate_content([prompt, img])  # Gemini multimodal call
    print(f"Query: {query}, Image: {image_path}, Response: {response.text.strip()}")
    try:
        score = int(response.text.strip()[0])
        if score in [0, 1, 2]:
            return score
    except Exception:
        pass
    return None

def evaluate_queries(queries, output_csv):
    for query in queries:
        try:
            result_dirs = main(query)
            if not result_dirs:
                raise Exception("No results returned for query.")
            for result_dir in result_dirs:
                score = gemini_evaluate_relevance(query, result_dir)
                result_dir = result_dir.replace(".jpg", ".png")
                with open(output_csv, "a") as f:
                    f.write(f"{query},{score},{result_dir}\n")
        except Exception as e:
            print(f"Error processing query '{query}': {e}")
            if 'result_dirs' in locals() and result_dirs:
                for result_dir in result_dirs:
                    with open(output_csv, "a") as f:
                        f.write(f"{query},None,{result_dir}\n")
            else:
                with open(output_csv, "a") as f:
                    f.write(f"{query},None,None\n")

if __name__ == "__main__":
    print("Evaluating memes...")
    evaluate_queries(meme_queries, "test_meme.csv")
    print("Evaluating meme templates...")
    evaluate_queries(template_queries, "test_template.csv")
